version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: learnpath_backend
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/backend/database
      - chroma_data:/app/backend/database/chroma_db
    env_file:
      - .env
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: learnpath_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  sqlite_data:
  chroma_data:
