# Curated resource library for popular technologies
CURATED_RESOURCES = {
    "Python": {
        "Official Documentation": "https://docs.python.org/3/",
        "Roadmap": "https://roadmap.sh/python",
        "Beginner Tutorial": "https://www.freecodecamp.org/news/python-crash-course/",
        "Advanced Tutorial": "https://realpython.com/",
        "YouTube Playlist": "https://www.youtube.com/playlist?list=PL-osiE80TeTskrapDnB_uDY29fX4P3M0H",
        "Practice Websites": "https://hackerrank.com/domains/python",
        "GitHub Repository": "https://github.com/vinta/awesome-python",
        "Cheat Sheet": "https://perso.limsi.fr/pointal/_media/python:cours:mementopython3-english.pdf",
        "Articles": "https://realpython.com/",
        "Books": "Fluent Python by Luciano Ramalho",
        "Certification Links": "https://pythoninstitute.org/certification/"
    },
    "Java": {
        "Official Documentation": "https://docs.oracle.com/en/java/",
        "Roadmap": "https://roadmap.sh/java",
        "Beginner Tutorial": "https://www.freecodecamp.org/news/java-programming-for-beginners/",
        "Advanced Tutorial": "https://www.baeldung.com/",
        "YouTube Playlist": "https://www.youtube.com/playlist?list=PLFE2CE09D83EE3E28",
        "Practice Websites": "https://www.hackerrank.com/domains/java",
        "GitHub Repository": "https://github.com/akullpp/awesome-java",
        "Cheat Sheet": "https://www.cheatography.com/davechild/cheat-sheets/java/",
        "Articles": "https://www.baeldung.com/",
        "Books": "Effective Java by Joshua Bloch",
        "Certification Links": "https://education.oracle.com/oracle-certified-professional-java-se-17-developer/pTrack_OCPJAVASE17"
    },
    "C": {
        "Official Documentation": "https://en.cppreference.com/w/c",
        "Roadmap": "https://roadmap.sh/c",
        "Beginner Tutorial": "https://www.freecodecamp.org/news/c-programming-for-beginners/",
        "Advanced Tutorial": "https://www.learn-c.org/",
        "YouTube Playlist": "https://www.youtube.com/watch?v=KJgsSFOSQv0",
        "Practice Websites": "https://www.hackerrank.com/domains/c",
        "GitHub Repository": "https://github.com/aleksandar-todorovic/awesome-c",
        "Cheat Sheet": "https://www.cheatography.com/ashlyn-black/cheat-sheets/c-reference/",
        "Articles": "https://www.geeksforgeeks.org/c-programming-language/",
        "Books": "The C Programming Language by Kernighan and Ritchie",
        "Certification Links": "https://cppinstitute.org/cla-c-programming-associate"
    },
    "C++": {
        "Official Documentation": "https://en.cppreference.com/w/cpp",
        "Roadmap": "https://roadmap.sh/cpp",
        "Beginner Tutorial": "https://www.freecodecamp.org/news/c-plus-plus-programming-tutorial/",
        "Advanced Tutorial": "https://www.learncpp.com/",
        "YouTube Playlist": "https://www.youtube.com/playlist?list=PLLrKBJ75H-HqL1mdG81bFEsxNKy2QsY8e",
        "Practice Websites": "https://www.hackerrank.com/domains/cpp",
        "GitHub Repository": "https://github.com/fffaraz/awesome-cpp",
        "Cheat Sheet": "https://www.cheatography.com/davechild/cheat-sheets/c-plus-plus/",
        "Articles": "https://isocpp.org/",
        "Books": "A Tour of C++ by Bjarne Stroustrup",
        "Certification Links": "https://cppinstitute.org/cpa-c-programming-associate"
    },
    "JavaScript": {
        "Official Documentation": "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
        "Roadmap": "https://roadmap.sh/javascript",
        "Beginner Tutorial": "https://javascript.info/",
        "Advanced Tutorial": "https://frontendmasters.com/books/javascript-hard-parts-v2/",
        "YouTube Playlist": "https://www.youtube.com/playlist?list=PLlasXeu85E9cQ32gLCgReGuywBSGbYyQA",
        "Practice Websites": "https://www.codewars.com/",
        "GitHub Repository": "https://github.com/sorrycc/awesome-javascript",
        "Cheat Sheet": "https://htmlcheatsheet.com/js/",
        "Articles": "https://javascript.info/",
        "Books": "You Don't Know JS by Kyle Simpson",
        "Certification Links": "https://www.w3schools.com/cert/cert_javascript.asp"
    },
    "TypeScript": {
        "Official Documentation": "https://www.typescriptlang.org/docs/",
        "Roadmap": "https://roadmap.sh/typescript",
        "Beginner Tutorial": "https://www.freecodecamp.org/news/learn-typescript-beginners-guide/",
        "Advanced Tutorial": "https://www.typescriptlang.org/docs/handbook/advanced-types.html",
        "YouTube Playlist": "https://www.youtube.com/watch?v=d56mG7DezGs",
        "Practice Websites": "https://www.typescriptlang.org/play",
        "GitHub Repository": "https://github.com/dzharii/awesome-typescript",
        "Cheat Sheet": "https://www.typescriptlang.org/docs/handbook/cheatsheets.html",
        "Articles": "https://dev.to/t/typescript",
        "Books": "Programming TypeScript by Boris Cherny",
        "Certification Links": "https://www.w3schools.com/cert/cert_typescript.asp"
    },
    "React": {
        "Official Documentation": "https://react.dev/",
        "Roadmap": "https://roadmap.sh/react",
        "Beginner Tutorial": "https://react.dev/learn",
        "Advanced Tutorial": "https://epicreact.dev/",
        "YouTube Playlist": "https://www.youtube.com/playlist?list=PL4cUxeGkcC9gZD-Tvwfod2gaISzfRiP9d",
        "Practice Websites": "https://react.dev/learn/tutorial-tic-tac-toe",
        "GitHub Repository": "https://github.com/enaqx/awesome-react",
        "Cheat Sheet": "https://reactcheatsheet.com/",
        "Articles": "https://dev.to/t/react",
        "Books": "Learning React by Alex Banks",
        "Certification Links": "https://www.w3schools.com/cert/cert_react.asp"
    },
    "Angular": {
        "Official Documentation": "https://angular.dev/",
        "Roadmap": "https://roadmap.sh/angular",
        "Beginner Tutorial": "https://angular.dev/tutorials",
        "Advanced Tutorial": "https://angular.dev/guide/routing",
        "YouTube Playlist": "https://www.youtube.com/playlist?list=PL4cUxeGkcC9i371QO_RtPp114FNLJQFJa",
        "Practice Websites": "https://stackblitz.com/",
        "GitHub Repository": "https://github.com/PatrickJS/awesome-angular",
        "Cheat Sheet": "https://angular.io/guide/cheatsheet",
        "Articles": "https://dev.to/t/angular",
        "Books": "Angular Projects by Aristeidis Bampakos",
        "Certification Links": "https://www.w3schools.com/cert/cert_angular.asp"
    },
    "Vue.js": {
        "Official Documentation": "https://vuejs.org/",
        "Roadmap": "https://roadmap.sh/vue",
        "Beginner Tutorial": "https://vuejs.org/guide/introduction.html",
        "Advanced Tutorial": "https://vuejs.org/guide/scaling-up/state-management.html",
        "YouTube Playlist": "https://www.youtube.com/playlist?list=PL4cUxeGkcC9hYYGbVPMcJWwCHUXRxIMfL",
        "Practice Websites": "https://sfc.vuejs.org/",
        "GitHub Repository": "https://github.com/vuejs/awesome-vue",
        "Cheat Sheet": "https://vuejs-cheat-sheet-v3.netlify.app/",
        "Articles": "https://dev.to/t/vue",
        "Books": "Testing Vue.js Applications by Edd Yerburgh",
        "Certification Links": "https://certification.vuejs.org/"
    },
    "Node.js": {
        "Official Documentation": "https://nodejs.org/docs/",
        "Roadmap": "https://roadmap.sh/nodejs",
        "Beginner Tutorial": "https://www.freecodecamp.org/news/introduction-to-nodejs/",
        "Advanced Tutorial": "https://nodejs.org/en/docs/guides/",
        "YouTube Playlist": "https://www.youtube.com/playlist?list=PL4cUxeGkcC9jsz4LDYc6kv3ymONOKxwBU",
        "Practice Websites": "https://node.school/",
        "GitHub Repository": "https://github.com/sindresorhus/awesome-nodejs",
        "Cheat Sheet": "https://devhints.io/nodejs",
        "Articles": "https://dev.to/t/node",
        "Books": "Node.js Design Patterns by Mario Casciaro",
        "Certification Links": "https://jslandia.org/nodejs-certification/"
    },
    "Express.js": {
        "Official Documentation": "https://expressjs.com/",
        "Roadmap": "https://roadmap.sh/nodejs",
        "Beginner Tutorial": "https://expressjs.com/en/starter/hello-world.html",
        "Advanced Tutorial": "https://expressjs.com/en/advanced/developing-templates.html",
        "YouTube Playlist": "https://www.youtube.com/watch?v=SccSCuHhOw0",
        "Practice Websites": "https://expressjs.com/en/resources/books-blogs.html",
        "GitHub Repository": "https://github.com/mjhea0/awesome-express",
        "Cheat Sheet": "https://devhints.io/express",
        "Articles": "https://medium.com/express-js",
        "Books": "Express in Action by Evan Hahn",
        "Certification Links": "https://www.w3schools.com/cert/default.asp"
    },
    "FastAPI": {
        "Official Documentation": "https://fastapi.tiangolo.com/",
        "Roadmap": "https://roadmap.sh/python",
        "Beginner Tutorial": "https://fastapi.tiangolo.com/tutorial/",
        "Advanced Tutorial": "https://fastapi.tiangolo.com/advanced/",
        "YouTube Playlist": "https://www.youtube.com/playlist?list=PL5gL_C27O_5ENh7e-3M7TzU4L4A2fU4L9",
        "Practice Websites": "https://fastapi.tiangolo.com/tutorial/first-steps/",
        "GitHub Repository": "https://github.com/mjhea0/awesome-fastapi",
        "Cheat Sheet": "https://github.com/leosousa/fastapi-cheat-sheet",
        "Articles": "https://testdriven.io/blog/topics/fastapi/",
        "Books": "Modern APIs with FastAPI by Michael Kennedy",
        "Certification Links": "https://www.w3schools.com/cert/default.asp"
    },
    "Django": {
        "Official Documentation": "https://docs.djangoproject.com/",
        "Roadmap": "https://roadmap.sh/python",
        "Beginner Tutorial": "https://docs.djangoproject.com/en/stable/intro/tutorial01/",
        "Advanced Tutorial": "https://docs.djangoproject.com/en/stable/topics/db/optimization/",
        "YouTube Playlist": "https://www.youtube.com/playlist?list=PL-osiE80TeTtoQCKZ03TU5fNzy1UyHrFn",
        "Practice Websites": "https://www.djangoproject.com/start/",
        "GitHub Repository": "https://github.com/wsvincent/awesome-django",
        "Cheat Sheet": "https://django-cheat-sheet.rdegges.com/",
        "Articles": "https://simpleisbetterthancomplex.com/",
        "Books": "Two Scoops of Django by Daniel Feldroy",
        "Certification Links": "https://www.w3schools.com/cert/default.asp"
    },
    "Flask": {
        "Official Documentation": "https://flask.palletsprojects.com/",
        "Roadmap": "https://roadmap.sh/python",
        "Beginner Tutorial": "https://flask.palletsprojects.com/en/stable/quickstart/",
        "Advanced Tutorial": "https://flask.palletsprojects.com/en/stable/patterns/",
        "YouTube Playlist": "https://www.youtube.com/playlist?list=PL-osiE80TeTs4UjLw5MM6OjgC5qyMxTy7",
        "Practice Websites": "https://flask.palletsprojects.com/",
        "GitHub Repository": "https://github.com/humiaozuzu/awesome-flask",
        "Cheat Sheet": "https://flask-cheat-sheet.readthedocs.io/",
        "Articles": "https://blog.miguelgrinberg.com/category/Flask",
        "Books": "Flask Web Development by Miguel Grinberg",
        "Certification Links": "https://www.w3schools.com/cert/default.asp"
    },
    "HTML": {
        "Official Documentation": "https://developer.mozilla.org/en-US/docs/Web/HTML",
        "Roadmap": "https://roadmap.sh/frontend",
        "Beginner Tutorial": "https://www.w3schools.com/html/",
        "Advanced Tutorial": "https://developer.mozilla.org/en-US/docs/Learn/HTML",
        "YouTube Playlist": "https://www.youtube.com/watch?v=pQN-PnMBDFI",
        "Practice Websites": "https://www.w3schools.com/html/html_exercises.asp",
        "GitHub Repository": "https://github.com/dypsilon/frontend-dev-bookmarks",
        "Cheat Sheet": "https://htmlcheatsheet.com/",
        "Articles": "https://css-tricks.com/",
        "Books": "HTML and CSS: Design and Build Websites by Jon Duckett",
        "Certification Links": "https://www.w3schools.com/cert/cert_html.asp"
    },
    "CSS": {
        "Official Documentation": "https://developer.mozilla.org/en-US/docs/Web/CSS",
        "Roadmap": "https://roadmap.sh/frontend",
        "Beginner Tutorial": "https://www.w3schools.com/css/",
        "Advanced Tutorial": "https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout",
        "YouTube Playlist": "https://www.youtube.com/playlist?list=PL4cUxeGkcC9gQeDH6xYGE1t1U87yU7g50",
        "Practice Websites": "https://cssgridgarden.com/",
        "GitHub Repository": "https://github.com/awesome-css-group/awesome-css",
        "Cheat Sheet": "https://htmlcheatsheet.com/css/",
        "Articles": "https://css-tricks.com/",
        "Books": "CSS Secrets by Lea Verou",
        "Certification Links": "https://www.w3schools.com/cert/cert_css.asp"
    },
    "Tailwind CSS": {
        "Official Documentation": "https://tailwindcss.com/docs",
        "Roadmap": "https://roadmap.sh/frontend",
        "Beginner Tutorial": "https://tailwindcss.com/docs/installation",
        "Advanced Tutorial": "https://tailwindcss.com/docs/reusing-styles",
        "YouTube Playlist": "https://www.youtube.com/playlist?list=PL4cUxeGkcC9gpXesKY1uRf2uxyYhDg73K",
        "Practice Websites": "https://play.tailwindcss.com/",
        "GitHub Repository": "https://github.com/anwarshah/awesome-tailwindcss",
        "Cheat Sheet": "https://nerdcave.com/tailwind-cheat-sheet",
        "Articles": "https://tailwindcss.com/blog",
        "Books": "Tailwind CSS Web Development by Jagoda Leszczynska",
        "Certification Links": "https://www.w3schools.com/cert/default.asp"
    },
    "Bootstrap": {
        "Official Documentation": "https://getbootstrap.com/docs/",
        "Roadmap": "https://roadmap.sh/frontend",
        "Beginner Tutorial": "https://getbootstrap.com/docs/5.3/getting-started/introduction/",
        "Advanced Tutorial": "https://getbootstrap.com/docs/5.3/customize/sass/",
        "YouTube Playlist": "https://www.youtube.com/playlist?list=PL4cUxeGkcC9i371QO_RtPp114FNLJQFJa",
        "Practice Websites": "https://www.w3schools.com/bootstrap5/index.php",
        "GitHub Repository": "https://github.com/bootstrap-association/awesome-bootstrap",
        "Cheat Sheet": "https://hackerthemes.com/bootstrap-cheatsheet/",
        "Articles": "https://blog.getbootstrap.com/",
        "Books": "Bootstrap 5 Quick Start by Jacob Lett",
        "Certification Links": "https://www.w3schools.com/cert/cert_bootstrap.asp"
    },
    "SQL": {
        "Official Documentation": "https://www.w3schools.com/sql/",
        "Roadmap": "https://roadmap.sh/postgresql-dba",
        "Beginner Tutorial": "https://sqlbolt.com/",
        "Advanced Tutorial": "https://use-the-index-luke.com/",
        "YouTube Playlist": "https://www.youtube.com/watch?v=HXV3zeQKqGY",
        "Practice Websites": "https://sqlzoo.net/",
        "GitHub Repository": "https://github.com/enqdev/awesome-sql",
        "Cheat Sheet": "https://web.sqldsp.com/sql-cheat-sheet/",
        "Articles": "https://modern-sql.com/",
        "Books": "SQL Queries for Mere Mortals by John Viescas",
        "Certification Links": "https://www.w3schools.com/cert/cert_sql.asp"
    },
    "MySQL": {
        "Official Documentation": "https://dev.mysql.com/doc/",
        "Roadmap": "https://roadmap.sh/postgresql-dba",
        "Beginner Tutorial": "https://www.mysqltutorial.org/",
        "Advanced Tutorial": "https://dev.mysql.com/doc/refman/8.0/en/optimization.html",
        "YouTube Playlist": "https://www.youtube.com/watch?v=7S_tz1z_5bA",
        "Practice Websites": "https://www.hackerrank.com/domains/sql",
        "GitHub Repository": "https://github.com/shlomi-noach/awesome-mysql",
        "Cheat Sheet": "https://devhints.io/mysql",
        "Articles": "https://planet.mysql.com/",
        "Books": "High Performance MySQL by Silvia Botros",
        "Certification Links": "https://education.oracle.com/mysql-8-0-database-developer/pTrack_102"
    },
    "PostgreSQL": {
        "Official Documentation": "https://www.postgresql.org/docs/",
        "Roadmap": "https://roadmap.sh/postgresql-dba",
        "Beginner Tutorial": "https://www.postgresqltutorial.com/",
        "Advanced Tutorial": "https://pgmustard.com/blog",
        "YouTube Playlist": "https://www.youtube.com/playlist?list=PL1B10E2D6A5D54FDE",
        "Practice Websites": "https://pgexercises.com/",
        "GitHub Repository": "https://github.com/dhamaniasad/awesome-postgres",
        "Cheat Sheet": "https://devhints.io/postgres",
        "Articles": "https://planet.postgresql.org/",
        "Books": "Designing Data-Intensive Applications by Martin Kleppmann",
        "Certification Links": "https://www.postgresql.ac.in/certification"
    },
    "MongoDB": {
        "Official Documentation": "https://www.mongodb.com/docs/",
        "Roadmap": "https://roadmap.sh/mongodb",
        "Beginner Tutorial": "https://learn.mongodb.com/",
        "Advanced Tutorial": "https://www.mongodb.com/docs/manual/core/aggregation-pipeline/",
        "YouTube Playlist": "https://www.youtube.com/playlist?list=PL4cUxeGkcC9h77dJ-ykFMb744M3y5VZCH",
        "Practice Websites": "https://university.mongodb.com/",
        "GitHub Repository": "https://github.com/ramnes/awesome-mongodb",
        "Cheat Sheet": "https://www.mongodb.com/developer/quickstart/cheat-sheet/",
        "Articles": "https://www.mongodb.com/blog",
        "Books": "MongoDB: The Definitive Guide by Shannon Bradshaw",
        "Certification Links": "https://learn.mongodb.com/pages/certification-program"
    },
    "Redis": {
        "Official Documentation": "https://redis.io/documentation",
        "Roadmap": "https://roadmap.sh/system-design",
        "Beginner Tutorial": "https://redis.io/docs/latest/develop/get-started/",
        "Advanced Tutorial": "https://redis.io/docs/latest/operate/oss_and_stack/reference/optimization/",
        "YouTube Playlist": "https://www.youtube.com/watch?v=jgpVdJB2sKQ",
        "Practice Websites": "https://redis.io/commands",
        "GitHub Repository": "https://github.com/jonof/awesome-redis",
        "Cheat Sheet": "https://devhints.io/redis",
        "Articles": "https://redis.com/blog/",
        "Books": "Redis in Action by Josiah Carlson",
        "Certification Links": "https://university.redis.com/certification/"
    },
    "Git": {
        "Official Documentation": "https://git-scm.com/doc",
        "Roadmap": "https://roadmap.sh/git-github",
        "Beginner Tutorial": "https://www.freecodecamp.org/news/git-and-github-for-beginners/",
        "Advanced Tutorial": "https://git-scm.com/book/en/v2",
        "YouTube Playlist": "https://www.youtube.com/playlist?list=PL4cUxeGkcC9goXbgTDQ0n_4TBzOO0ocPR",
        "Practice Websites": "https://learngitbranching.js.org/",
        "GitHub Repository": "https://github.com/dictcp/awesome-git",
        "Cheat Sheet": "https://education.github.com/git-cheat-sheet-education.pdf",
        "Articles": "https://github.blog/",
        "Books": "Pro Git by Scott Chacon",
        "Certification Links": "https://www.w3schools.com/cert/default.asp"
    },
    "GitHub": {
        "Official Documentation": "https://docs.github.com/",
        "Roadmap": "https://roadmap.sh/git-github",
        "Beginner Tutorial": "https://docs.github.com/en/get-started",
        "Advanced Tutorial": "https://docs.github.com/en/actions",
        "YouTube Playlist": "https://www.youtube.com/watch?v=apGV9Ad7XYY",
        "Practice Websites": "https://lab.github.com/",
        "GitHub Repository": "https://github.com/github/docs",
        "Cheat Sheet": "https://github.com/tiimgreen/github-cheat-sheet",
        "Articles": "https://github.blog/category/engineering/",
        "Books": "Introducing GitHub by Peter Bell",
        "Certification Links": "https://resources.github.com/learn/certifications/"
    },
    "Linux": {
        "Official Documentation": "https://www.kernel.org/doc/html/latest/",
        "Roadmap": "https://roadmap.sh/linux",
        "Beginner Tutorial": "https://linuxjourney.com/",
        "Advanced Tutorial": "https://www.linuxdoc.org/",
        "YouTube Playlist": "https://www.youtube.com/watch?v=wBp0Rb-ZJak",
        "Practice Websites": "https://www.overthewire.org/wargames/bandit/",
        "GitHub Repository": "https://github.com/alvarotrivial/awesome-linux",
        "Cheat Sheet": "https://devhints.io/bash",
        "Articles": "https://www.linux.com/news/",
        "Books": "The Linux Command Line by William Shotts",
        "Certification Links": "https://www.lpi.org/our-certifications/linux-essentials-overview"
    },
    "Docker": {
        "Official Documentation": "https://docs.docker.com/",
        "Roadmap": "https://roadmap.sh/docker",
        "Beginner Tutorial": "https://docs.docker.com/get-started/",
        "Advanced Tutorial": "https://docs.docker.com/develop/develop-images/dockerfile_best-practices/",
        "YouTube Playlist": "https://www.youtube.com/watch?v=3c-iMh1Y984",
        "Practice Websites": "https://labs.play-with-docker.com/",
        "GitHub Repository": "https://github.com/veggiemonk/awesome-docker",
        "Cheat Sheet": "https://dockerlabs.collabnix.com/docker/cheatsheet/",
        "Articles": "https://www.docker.com/blog/",
        "Books": "Docker Deep Dive by Nigel Poulton",
        "Certification Links": "https://training.mirantis.com/certification/docker-certified-associate/"
    },
    "Kubernetes": {
        "Official Documentation": "https://kubernetes.io/docs/",
        "Roadmap": "https://roadmap.sh/kubernetes",
        "Beginner Tutorial": "https://kubernetes.io/docs/tutorials/",
        "Advanced Tutorial": "https://kubernetes.io/docs/tasks/administer-cluster/",
        "YouTube Playlist": "https://www.youtube.com/playlist?list=PLI2S-EY-G1aW85Jj1o8f9JlgY3g92GZwt",
        "Practice Websites": "https://labs.play-with-k8s.com/",
        "GitHub Repository": "https://github.com/ramitsurana/awesome-kubernetes",
        "Cheat Sheet": "https://kubernetes.io/docs/reference/kubectl/cheatsheet/",
        "Articles": "https://kubernetes.io/blog/",
        "Books": "Kubernetes Up and Running by Kelsey Hightower",
        "Certification Links": "https://training.linuxfoundation.org/certification/certified-kubernetes-administrator-cka/"
    },
    "AWS": {
        "Official Documentation": "https://docs.aws.amazon.com/",
        "Roadmap": "https://roadmap.sh/aws",
        "Beginner Tutorial": "https://aws.amazon.com/getting-started/",
        "Advanced Tutorial": "https://aws.amazon.com/architecture/",
        "YouTube Playlist": "https://www.youtube.com/watch?v=SOTamWNgDKc",
        "Practice Websites": "https://aws.amazon.com/free/",
        "GitHub Repository": "https://github.com/donnemartin/awesome-aws",
        "Cheat Sheet": "https://jayendrapatil.com/aws-cheat-sheets/",
        "Articles": "https://aws.amazon.com/blogs/aws/",
        "Books": "AWS Certified Solutions Architect Study Guide by Ben Piper",
        "Certification Links": "https://aws.amazon.com/certification/"
    },
    "Azure": {
        "Official Documentation": "https://learn.microsoft.com/en-us/azure/",
        "Roadmap": "https://roadmap.sh/devops",
        "Beginner Tutorial": "https://learn.microsoft.com/en-us/training/paths/azure-fundamentals/",
        "Advanced Tutorial": "https://learn.microsoft.com/en-us/azure/architecture/",
        "YouTube Playlist": "https://www.youtube.com/playlist?list=PLlVtbbgaxc2wl0Vv1MeeLKCxMvIpKmP5t",
        "Practice Websites": "https://azure.microsoft.com/en-us/free/",
        "GitHub Repository": "https://github.com/alefranz/awesome-azure",
        "Cheat Sheet": "https://github.com/Piotr1215/awesome-azure-architecture",
        "Articles": "https://azure.microsoft.com/en-us/blog/",
        "Books": "Microsoft Azure Infrastructure Services by John Savill",
        "Certification Links": "https://learn.microsoft.com/en-us/credentials/browse/?credential_types=certification"
    },
    "GCP": {
        "Official Documentation": "https://cloud.google.com/docs",
        "Roadmap": "https://roadmap.sh/devops",
        "Beginner Tutorial": "https://cloud.google.com/training",
        "Advanced Tutorial": "https://cloud.google.com/architecture",
        "YouTube Playlist": "https://www.youtube.com/playlist?list=PLIivdWyY5sqKk7sVf58wXjJ1I02nI9Y5m",
        "Practice Websites": "https://cloud.google.com/free",
        "GitHub Repository": "https://github.com/jessfraz/awesome-gcp",
        "Cheat Sheet": "https://github.com/gregsramblings/google-cloud-4-words",
        "Articles": "https://cloud.google.com/blog/",
        "Books": "Official Google Cloud Certified Professional Cloud Architect Study Guide by Dan Sullivan",
        "Certification Links": "https://cloud.google.com/learn/certification"
    },
    "Machine Learning": {
        "Official Documentation": "https://scikit-learn.org/stable/",
        "Roadmap": "https://roadmap.sh/ai",
        "Beginner Tutorial": "https://www.freecodecamp.org/news/machine-learning-mean-median-mode-standard-deviation-percentiles/",
        "Advanced Tutorial": "https://scikit-learn.org/stable/modules/grid_search.html",
        "YouTube Playlist": "https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab",
        "Practice Websites": "https://www.kaggle.com/",
        "GitHub Repository": "https://github.com/josephmisiti/awesome-machine-learning",
        "Cheat Sheet": "https://github.com/soulmachine/machine-learning-cheat-sheet",
        "Articles": "https://distill.pub/",
        "Books": "Hands-On Machine Learning by Aurélien Géron",
        "Certification Links": "https://www.coursera.org/specializations/machine-learning-introduction"
    },
    "Deep Learning": {
        "Official Documentation": "https://pytorch.org/docs/",
        "Roadmap": "https://roadmap.sh/ai",
        "Beginner Tutorial": "https://www.deeplearning.ai/",
        "Advanced Tutorial": "https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html",
        "YouTube Playlist": "https://www.youtube.com/playlist?list=PLtBw6njReaaeAEXesVpGAfMc2D1L63e46",
        "Practice Websites": "https://www.kaggle.com/",
        "GitHub Repository": "https://github.com/ChristosChristofidis/awesome-deep-learning",
        "Cheat Sheet": "https://github.com/kengz/deep-learning-cheat-sheet",
        "Articles": "https://distill.pub/",
        "Books": "Deep Learning by Ian Goodfellow",
        "Certification Links": "https://www.deeplearning.ai/program/deep-learning-specialization/"
    },
    "Data Science": {
        "Official Documentation": "https://pandas.pydata.org/docs/",
        "Roadmap": "https://roadmap.sh/data-analyst",
        "Beginner Tutorial": "https://www.freecodecamp.org/news/data-science-course-for-beginners/",
        "Advanced Tutorial": "https://pandas.pydata.org/docs/user_guide/enhancingperf.html",
        "YouTube Playlist": "https://www.youtube.com/playlist?list=PL2y1Axd1J3tjoS-VvNAs_zLz7OndSgIEg",
        "Practice Websites": "https://www.kaggle.com/datasets",
        "GitHub Repository": "https://github.com/okulbilisim/awesome-data-science",
        "Cheat Sheet": "https://github.com/FavioVazquez/ds-cheatsheets",
        "Articles": "https://towardsdatascience.com/",
        "Books": "Python for Data Analysis by Wes McKinney",
        "Certification Links": "https://www.coursera.org/professional-certificates/ibm-data-science"
    },
    "Pandas": {
        "Official Documentation": "https://pandas.pydata.org/docs/",
        "Roadmap": "https://roadmap.sh/data-analyst",
        "Beginner Tutorial": "https://pandas.pydata.org/docs/user_guide/10min.html",
        "Advanced Tutorial": "https://pandas.pydata.org/docs/user_guide/enhancingperf.html",
        "YouTube Playlist": "https://www.youtube.com/playlist?list=PL5-da3qGB5ICCsgW1MkbuaEqGDSpDRAyb",
        "Practice Websites": "https://github.com/guipsamora/pandas_exercises",
        "GitHub Repository": "https://github.com/pandas-dev/pandas",
        "Cheat Sheet": "https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf",
        "Articles": "https://towardsdatascience.com/tagged/pandas",
        "Books": "Python for Data Analysis by Wes McKinney",
        "Certification Links": "https://www.w3schools.com/cert/default.asp"
    },
    "NumPy": {
        "Official Documentation": "https://numpy.org/doc/",
        "Roadmap": "https://roadmap.sh/ai",
        "Beginner Tutorial": "https://numpy.org/doc/stable/user/absolute_beginners.html",
        "Advanced Tutorial": "https://numpy.org/doc/stable/user/basics.broadcasting.html",
        "YouTube Playlist": "https://www.youtube.com/watch?v=QUT1VHiLgKQ",
        "Practice Websites": "https://github.com/rougier/numpy-100",
        "GitHub Repository": "https://github.com/numpy/numpy",
        "Cheat Sheet": "https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf",
        "Articles": "https://realpython.com/numpy-tutorial/",
        "Books": "Guide to NumPy by Travis Oliphant",
        "Certification Links": "https://www.w3schools.com/cert/default.asp"
    },
    "Scikit-learn": {
        "Official Documentation": "https://scikit-learn.org/",
        "Roadmap": "https://roadmap.sh/ai",
        "Beginner Tutorial": "https://scikit-learn.org/stable/tutorial/basic/tutorial.html",
        "Advanced Tutorial": "https://scikit-learn.org/stable/modules/model_evaluation.html",
        "YouTube Playlist": "https://www.youtube.com/playlist?list=PL5-da3qGB5ICeMbvS62MzyZsOBylmNoo5",
        "Practice Websites": "https://www.kaggle.com/code",
        "GitHub Repository": "https://github.com/scikit-learn/scikit-learn",
        "Cheat Sheet": "https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Scikit_Learn_Cheat_Sheet_Python.pdf",
        "Articles": "https://towardsdatascience.com/tagged/scikit-learn",
        "Books": "Introduction to Machine Learning with Python by Andreas Müller",
        "Certification Links": "https://www.coursera.org/specializations/machine-learning-introduction"
    },
    "TensorFlow": {
        "Official Documentation": "https://www.tensorflow.org/api_docs",
        "Roadmap": "https://roadmap.sh/ai",
        "Beginner Tutorial": "https://www.tensorflow.org/tutorials/quickstart/beginner",
        "Advanced Tutorial": "https://www.tensorflow.org/tutorials/generative/dcgan",
        "YouTube Playlist": "https://www.youtube.com/playlist?list=PLQY2H8rRoyqyLbz3H5xTXGX3hYQHPAUus",
        "Practice Websites": "https://playgound.tensorflow.org/",
        "GitHub Repository": "https://github.com/tensorflow/tensorflow",
        "Cheat Sheet": "https://github.com/jaredlandau/tensorflow-cheat-sheet",
        "Articles": "https://blog.tensorflow.org/",
        "Books": "Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow by Aurélien Géron",
        "Certification Links": "https://www.tensorflow.org/certificate"
    },
    "PyTorch": {
        "Official Documentation": "https://pytorch.org/docs/",
        "Roadmap": "https://roadmap.sh/ai",
        "Beginner Tutorial": "https://pytorch.org/tutorials/beginner/basics/intro.html",
        "Advanced Tutorial": "https://pytorch.org/tutorials/recipes/recipes_index.html",
        "YouTube Playlist": "https://www.youtube.com/playlist?list=PLqnslRFeH2UrcDBWF5mfPGgQDAniPE8MY",
        "Practice Websites": "https://pytorch.org/tutorials/",
        "GitHub Repository": "https://github.com/pytorch/pytorch",
        "Cheat Sheet": "https://pytorch.org/tutorials/beginner/ptcheat.html",
        "Articles": "https://pytorch.org/blog/",
        "Books": "Deep Learning with PyTorch by Eli Stevens",
        "Certification Links": "https://www.coursera.org/specializations/deep-learning-pytorch"
    },
    "NLP": {
        "Official Documentation": "https://www.huggingface.co/docs/transformers/index",
        "Roadmap": "https://roadmap.sh/ai",
        "Beginner Tutorial": "https://www.huggingface.co/learn/nlp-course/",
        "Advanced Tutorial": "https://huggingface.co/docs/transformers/main_classes/trainer",
        "YouTube Playlist": "https://www.youtube.com/playlist?list=PLoROMvodv4rOhwG5PxzT5spn73Dd7vAxi",
        "Practice Websites": "https://huggingface.co/tasks/translation",
        "GitHub Repository": "https://github.com/keon/awesome-nlp",
        "Cheat Sheet": "https://github.com/yvespeirsman/nlp-cheat-sheet",
        "Articles": "https://huggingface.co/blog",
        "Books": "Speech and Language Processing by Dan Jurafsky",
        "Certification Links": "https://huggingface.co/learn/nlp-course"
    },
    "Computer Vision": {
        "Official Documentation": "https://opencv.org/",
        "Roadmap": "https://roadmap.sh/ai",
        "Beginner Tutorial": "https://docs.opencv.org/4.x/d9/df8/tutorial_root.html",
        "Advanced Tutorial": "https://docs.opencv.org/4.x/d2/d64/tutorial_table_of_content_objdetect.html",
        "YouTube Playlist": "https://www.youtube.com/watch?v=oXlwWbU8l2o",
        "Practice Websites": "https://opencv.org/courses/",
        "GitHub Repository": "https://github.com/jbhuang0604/awesome-computer-vision",
        "Cheat Sheet": "https://github.com/karan/open-cv-cheat-sheet",
        "Articles": "https://learnopencv.com/",
        "Books": "Computer Vision: Algorithms and Applications by Richard Szeliski",
        "Certification Links": "https://opencv.org/courses/"
    },
    "LangChain": {
        "Official Documentation": "https://python.langchain.com/",
        "Roadmap": "https://roadmap.sh/ai",
        "Beginner Tutorial": "https://python.langchain.com/v0.2/docs/tutorials/",
        "Advanced Tutorial": "https://python.langchain.com/v0.2/docs/how_to/",
        "YouTube Playlist": "https://www.youtube.com/playlist?list=PL8motc6AQftw1pOn0JchQ8M26N8mC9g27",
        "Practice Websites": "https://github.com/langchain-ai/langchain",
        "GitHub Repository": "https://github.com/langchain-ai/awesome-langchain",
        "Cheat Sheet": "https://github.com/gkamradt/langchain-tutorials",
        "Articles": "https://blog.langchain.dev/",
        "Books": "LangChain in Action by Jacob Lee",
        "Certification Links": "https://www.deeplearning.ai/short-courses/langchain-for-llm-application-development/"
    },
    "RAG": {
        "Official Documentation": "https://docs.llamaindex.ai/en/stable/",
        "Roadmap": "https://roadmap.sh/ai",
        "Beginner Tutorial": "https://python.langchain.com/v0.2/docs/tutorials/rag/",
        "Advanced Tutorial": "https://docs.llamaindex.ai/en/stable/optimizing/production_rag/",
        "YouTube Playlist": "https://www.youtube.com/watch?v=wd7TZ4w1mSw",
        "Practice Websites": "https://github.com/run-llama/llama_index",
        "GitHub Repository": "https://github.com/semi-technologies/awesome-rag",
        "Cheat Sheet": "https://towardsdatascience.com/retrieval-augmented-generation-rag-cheat-sheet-2dec40a6b7d5",
        "Articles": "https://towardsdatascience.com/retrieval-augmented-generation-rag-from-theory-to-langchain-implementation-4e366034c6c2",
        "Books": "Retrieval-Augmented Generation by Microsoft Research",
        "Certification Links": "https://www.deeplearning.ai/short-courses/building-evaluating-advanced-rag/"
    },
    "Prompt Engineering": {
        "Official Documentation": "https://www.promptingguide.ai/",
        "Roadmap": "https://roadmap.sh/ai",
        "Beginner Tutorial": "https://www.promptingguide.ai/introduction",
        "Advanced Tutorial": "https://www.promptingguide.ai/techniques/tot",
        "YouTube Playlist": "https://www.youtube.com/watch?v=dOxUtcXP0To",
        "Practice Websites": "https://playground.openai.com/",
        "GitHub Repository": "https://github.com/dictcp/awesome-chatgpt-prompts",
        "Cheat Sheet": "https://github.com/f/awesome-chatgpt-prompts",
        "Articles": "https://lilianweng.github.io/posts/2023-03-15-prompt-engineering/",
        "Books": "The Art of Prompt Engineering by Leo Xen",
        "Certification Links": "https://www.deeplearning.ai/short-courses/chatgpt-prompt-eng-for-developers/"
    },
    "LLM": {
        "Official Documentation": "https://huggingface.co/docs/transformers/index",
        "Roadmap": "https://roadmap.sh/ai",
        "Beginner Tutorial": "https://www.deeplearning.ai/short-courses/large-language-models-semantic-search/",
        "Advanced Tutorial": "https://huggingface.co/docs/transformers/generation_strategies",
        "YouTube Playlist": "https://www.youtube.com/playlist?list=PLoROMvodv4rNiJRchCzutFw5ItRjZ570G",
        "Practice Websites": "https://chat.lmsys.org/",
        "GitHub Repository": "https://github.com/Hannibal046/Awesome-LLM",
        "Cheat Sheet": "https://github.com/Mooler0410/LLMs-Practical-Guide",
        "Articles": "https://karpathy.medium.com/a-path-to-general-artificial-intelligence-3b7f1687f874",
        "Books": "Large Language Models in Action by Tyler Warden",
        "Certification Links": "https://www.deeplearning.ai/short-courses/"
    },
    "Generative AI": {
        "Official Documentation": "https://developers.google.com/machine-learning/gan",
        "Roadmap": "https://roadmap.sh/ai",
        "Beginner Tutorial": "https://www.coursera.org/learn/introduction-to-generative-ai",
        "Advanced Tutorial": "https://github.com/google/generative-ai-python",
        "YouTube Playlist": "https://www.youtube.com/watch?v=G2fqAlgmoPo",
        "Practice Websites": "https://aistudio.google.com/",
        "GitHub Repository": "https://github.com/steven2358/awesome-generative-ai",
        "Cheat Sheet": "https://github.com/dair-ai/Prompt-Engineering-Guide",
        "Articles": "https://openai.com/research",
        "Books": "Generative Deep Learning by David Foster",
        "Certification Links": "https://cloud.google.com/learn/certification"
    }
}
